labs/urls.py
# -*- encoding: utf-8 -*-
from django.conf.urls import url

from labs.views import SubmitLab, ViewLab

urlpatterns = [
    url(r'^lab/(?P<lab_id>\d+)/submit$', SubmitLab.as_view(),
        name='submit_lab'),
    url(r'^lab/(?P<lab_id>\d+)/view$', ViewLab.as_view(),
        name='view_lab'),
]

open_labs/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin

from open_labs.views import Home, RegistrationView


urlpatterns = [
    url(r'^$', Home.as_view(), name='home'),
    url(r'^admin/', admin.site.urls),
    url(r'^', include('django.contrib.auth.urls')),
    url(r'^register/$', RegistrationView.as_view(), name='register'),
    # url(r'^', include('registration.backends.simple.urls')),
    url(r'^', include('labs.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

labs/models.py
# -*- encoding: utf-8 -*-
from django.db import models


class Lab(models.Model):
    title = models.CharField(max_length=256, default='', blank=True)
    description = models.TextField(blank=True)
    teacher = models.ForeignKey('personnel.User')

    def __str__(self):
        return self.title


class DefinitionAttachment(models.Model):
    file = models.FileField(upload_to='lab-definitions')
    lab = models.ForeignKey(Lab, related_name='attachments')


class Result(models.Model):
    file = models.FileField(upload_to='lab-results')
    lab = models.ForeignKey(Lab)
    student = models.ForeignKey('personnel.User')

personnel/models.py
# -*- encoding: utf-8 -*-
from django.contrib.auth.models import AbstractUser
from django.db import models


class Group(models.Model):
    name = models.CharField(max_length=256)
    students = models.ManyToManyField('personnel.User', blank=True)
    labs = models.ManyToManyField('labs.Lab', blank=True)

    def __str__(self):
        return self.name


class User(AbstractUser):
    class Meta:
        db_table = 'auth_user'

    def __str__(self):
        return '{} {}'.format(self.last_name, self.first_name) or self.username

labs/forms.py
# -*- encoding: utf-8 -*-
from django.forms import ModelForm

from labs.models import Result


class SubmitResultForm(ModelForm):
    class Meta:
        model = Result
        fields = ['file']

labs/views.py
# -*- encoding: utf-8 -*-
from django.contrib.auth.decorators import login_required
from django.urls.base import reverse
from django.utils.decorators import method_decorator
from django.views.generic import ListView
from django.views.generic.edit import CreateView

from labs.models import Result, Lab
from labs.forms import SubmitResultForm


@method_decorator(login_required(login_url='login'), name='dispatch')
class SubmitLab(CreateView):
    model = Result
    form_class = SubmitResultForm

    def get_success_url(self):
        return reverse('view_lab', kwargs={'lab_id': self.kwargs['lab_id']})

    def form_valid(self, form):
        form.instance.lab_id = self.kwargs['lab_id']
        form.instance.student = self.request.user
        return super(SubmitLab, self).form_valid(form)


@method_decorator(login_required(login_url='login'), name='dispatch')
class ViewLab(ListView):
    model = Result
    paginate_by = 100

    def get_context_data(self, **kwargs):
        return super(ViewLab, self).get_context_data(
            lab=Lab.objects.get(id=self.kwargs['lab_id']), **kwargs)

    def get_queryset(self):
        return self.model.objects.filter(student=self.request.user)

open_labs/views.py
# -*- encoding: utf-8 -*-
from django import forms
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import Group as Role
from django.shortcuts import redirect
from django.utils.decorators import method_decorator
from django.views.generic import TemplateView

from registration.views import (
    RegistrationView as RegView, RegistrationForm as RegForm
)

from personnel.models import Group, User


@method_decorator(login_required(login_url='login'), name='dispatch')
class Home(TemplateView):
    template_name = 'open_labs/home.html'

    def get_context_data(self, **kwargs):
        kwargs.update({
            'teacher': Role.objects.get(name='Teacher'),
            'student': Role.objects.get(name='Student'),
        })
        return kwargs


class RegistrationForm(RegForm):
    email = forms.EmailField(help_text='email address')
    role = forms.ModelChoiceField(queryset=Role.objects.all(),
                                  initial=Role.objects.get(name='Student'))
    group = forms.ModelChoiceField(queryset=Group.objects.all())

    class Meta(RegForm.Meta):
        fields = [
            User.USERNAME_FIELD,
            'first_name',
            'last_name',
            'email',
            'password1',
            'password2',
        ]


class RegistrationView(RegView):
    form_class = RegistrationForm
    success_url = 'home'

    def form_valid(self, form: RegistrationForm):
        instance = form.save()
        instance = User.objects.get(id=instance.id)
        instance.groups.add(form.cleaned_data['role'])
        instance.group_set.add(form.cleaned_data['group'])
        return redirect(self.success_url)

templates/labs/result_form.html
{% extends 'open_labs/base.html' %}

{% load bootstrap3 %}

{% block bootstrap3_content %}
{{ block.super }}
<div class="container">
    {% if form.is_multipart %}
    <form enctype="multipart/form-data" class="form" method="post">
    {% else %}
    <form class="form" method="post">
    {% endif %}
        {% csrf_token %}
        {% bootstrap_form form %}
        {% buttons %}
            <input type="submit" value="Submit" class="btn btn-primary"/>
        {% endbuttons %}
    </form>
</div>
{% endblock %}

templates/labs/result_list.html
{% extends 'open_labs/base.html' %}

{% load bootstrap3 %}

{% block bootstrap3_content %}
    {{ block.super }}
    <div class="container">
        <h3>{{ lab.title }}</h3>
        <p>
            {{ lab.description }}
        </p>
        <ul>
            {% for attachment in lab.attachments.all %}
                <li><a href="{{ attachment.file.url }}">{{ attachment.file }}</a></li>
            {% endfor %}
        </ul>
        <hr>
        <ul>
        {% for result in object_list %}
            <li>
                <a href="{{ result.file.url }}">{{ result.file }}</a>
            </li>
        {% endfor %}
        </ul>
        <a href="{% url 'submit_lab' lab.id %}" class="btn btn-default">Submit result</a>
    </div>
{% endblock %}

templates/open_labs/base.html
{% extends 'bootstrap3/bootstrap3.html' %}
{% load bootstrap3 %}

{% block bootstrap3_extra_head %}
    {{ block.super }}
    <style>
    body {
      min-height: 2000px;
      padding-top: 70px;
    }
    </style>
{% endblock %}

{% block bootstrap3_content %}
    <!-- Fixed navbar -->
    <nav class="navbar navbar-default navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="{% url 'home' %}">Open labs</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav navbar-right">
            {% if request.user %}<li><a href="#">{{ request.user.first_name }} {{ request.user.last_name }}</a></li>{% endif %}
            {% if request.user.is_authenticated %}<li><a href="{% url 'logout' %}">Logout</a></li>{% else %}<li><a href="{% url 'login' %}">Login</a></li>{% endif %}
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>
{% endblock %}

templates/open_labs/home.html
{% extends 'open_labs/base.html' %}

{% block bootstrap3_content %}
    {{ block.super }}
    <div class="container">
    {% if student in request.user.groups.all %}
        {% include 'open_labs/student/lab_list.html' %}
    {% elif teacher in request.user.groups.all %}
        teacher
    {% else %}
        no group
    {% endif %}
    </div>
{% endblock %}

templates/open_labs/student/lab_list.html
{% for group in request.user.group_set.all %}
    <h3>Group: {{ group.name }}</h3>
    <ul>
        {% for lab in group.labs.all %}
            {{ lab.title }}
            <a href="{% url 'view_lab' lab.id %}" class="btn btn-default">View</a>
            <a href="{% url 'submit_lab' lab.id %}" class="btn btn-default">Submit result</a>
        {% endfor %}
    </ul>
{% endfor %}